language: go

go:
  # Please keep this in-sync with the go version we build against in
  # build-support/docker/Build-Go.dockerfile.
  - "1.12.1"
  
matrix:
  include:
    - os: linux # x86_64 queue name
      env: GOTEST_PKGS="./api"
    - os: linux # x86_64 queue name
      env: GOTEST_PKGS="./agent"
    - os: linux # x86_64 queue name
      env: GOTEST_PKGS="./agent/consul"
    - os: linux # x86_64 queue name
      env: GOTEST_PKGS_EXCLUDE="./api|./agent|./agent/consul"
    - os: linux-ppc64le # power queue name
      env: GOTEST_PKGS="./api"
    - os: linux-ppc64le # power queue name
      env: GOTEST_PKGS="./agent"
    - os: linux-ppc64le # power queue name
      env: GOTEST_PKGS="./agent/consul"
    - os: linux-ppc64le # power queue name
      env: GOTEST_PKGS_EXCLUDE="./api|./agent|./agent/consul"
    
branches:
  only:
    - master
    - f-acl-ux



script:
  - make test-ci

sudo: false
